# Generated by Django 3.0.6 on 2020-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
