# Generated by Django 3.0.6 on 2020-05-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='notes',
            field=models.TextField(),
        ),
    ]
