# Generated by Django 3.0.6 on 2020-06-01 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200529_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 12, 31, 10, 6573, tzinfo=utc)),
        ),
    ]
