# Generated by Django 3.0.6 on 2020-06-02 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200601_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 9, 22, 48, 608682, tzinfo=utc)),
        ),
    ]
