# Generated by Django 3.0.6 on 2020-06-02 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200602_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 9, 33, 18, 888369, tzinfo=utc)),
        ),
    ]
